-- -----------------------------------------------------------------------------
-- ORDERS TABLE
-- -----------------------------------------------------------------------------
-- This script runs automatically the first time the PostgreSQL container
-- starts. It creates the table that the Inventory Service will use to
-- persist order data received from Kafka.
--
-- In a real system, schema management would be handled by a migration tool
-- such as Alembic (Python) or Flyway (Java). For this lab, a single SQL
-- script is sufficient.
--
-- The SQLAlchemy ORM model in models.py mirrors this schema exactly.
-- The two approaches — raw SQL and ORM — achieve the same result.
-- The SQL file is the source of truth for the schema; the ORM model is
-- the Python layer that maps to it.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS orders (
    -- The order_id is generated by the producer (uuid4) and used as the
    -- Kafka message key. It uniquely identifies each order.
    order_id        VARCHAR(36)     PRIMARY KEY,

    client_fname    VARCHAR(100)    NOT NULL,
    item            VARCHAR(100)    NOT NULL,
    order_quantity  INTEGER         NOT NULL,

    -- received_at records when the Inventory Service consumed this message.
    -- This is the database insertion time, not the time the order was placed.
    received_at     TIMESTAMP       DEFAULT NOW()
);